# Generated by Django 6.0.4 on 2026-04-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text="What's on your mind?")),
                ('code_snippet', models.TextField(blank=True, help_text='Share some code!')),
                ('media', models.FileField(blank=True, help_text='Upload an image or video', null=True, upload_to='post_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers', 'Followers Only'), ('specific', 'Specific Users')], default='public', max_length=20)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text="Select users if privacy is 'Specific Users'", related_name='allowed_posts', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
