# Generated by Django 6.0.4 on 2026-04-16 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Feedback'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_post_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abusive Content'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Material'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_likes', models.BooleanField(default=True)),
                ('notify_comments', models.BooleanField(default=True)),
                ('notify_follows', models.BooleanField(default=True)),
                ('notify_mentions', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('allow_messages_from', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('private_account', models.BooleanField(default=False)),
                ('theme', models.CharField(default='dark', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
